spring.application.name=Ledgermate

# Use in-memory H2 database (no external DB needed)
#spring.datasource.url=jdbc:h2:mem:ledgermate;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:mysql://localhost:3306/ledger_demo
spring.datasource.username=root
spring.datasource.password=skillledger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automatically create/update tables from JPA entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable H2 web console at /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Log SQL and parameters at a reasonable level
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

